## Adapted from https://github.com/vdemichev/DiaNN/issues/1202#issuecomment-2417108281
FROM ubuntu:24.04
#USER root
ENV DEBIAN_FRONTEND=noninteractive

# Update package lists and ensure package versions are up to date
RUN apt-get update && apt-get upgrade -y

# Install necessary packages including locales
RUN apt-get install wget unzip libgomp1 locales -y

# Configure locale to avoid runtime errors
RUN locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8

# Set environment variables for locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Download DIA-NN version <version>
RUN wget https://github.com/vdemichev/DiaNN/releases/download/2.0/DIA-NN-2.2.0-Academia-Linux.zip -O diann-2.2.0.Linux.zip
#RUN wget https://github.com/vdemichev/DiaNN/releases/download/<version>/diann-<version>.Linux.zip -O diann-<version>.Linux.zip

# Unzip the DIA-NN package
RUN unzip diann-2.2.0.Linux.zip

# Set appropriate permissions for the DIA-NN folder
RUN chmod -R 775 /diann-2.2.0

# NOTE: It is entirely the user's responsibility to ensure compliance with DIA-NN license terms.
# Please review the licensing terms for DIA-NN before using or distributing this Docker image.

# CLI Reference: https://github.com/vdemichev/DiaNN?tab=readme-ov-file#command-line-reference

